name:                nixfmt
version:             0.0.0.0
github:              "NorfairKingnixfmt"
license:             BSD3
author:              "Tom Sydney Kerckhove
maintainer:          "example@example.com"
copyright:           "2018 Tom Sydney Kerckhove"

extra-source-files:
- README.md
- ChangeLog.md
description:         Please see the README on GitHub at <https://github.com/githubuser/nixfmt#readme>

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - hnix

executables:
  nixfmt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - nixfmt

tests:
  nixfmt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - nixfmt
